<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Default implementation for FTP, SMB, LocalDisk protocol on backend</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Polly" Version="8.4.1" />
    <PackageReference Include="FluentFTP" Version="51.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MicrosoftExtensionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Juice.Storage.Abstractions\Juice.Storage.Abstractions.csproj" />
  </ItemGroup>

</Project>
